*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMV_ZFIR057AT1..................................*
FORM GET_DATA_ZMV_ZFIR057AT1.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFIR057AT1 WHERE
(VIM_WHERETAB) .
    CLEAR ZMV_ZFIR057AT1 .
ZMV_ZFIR057AT1-MANDT =
ZFIR057AT1-MANDT .
ZMV_ZFIR057AT1-PROGNAME =
ZFIR057AT1-PROGNAME .
ZMV_ZFIR057AT1-VARIANT =
ZFIR057AT1-VARIANT .
ZMV_ZFIR057AT1-ZSFYEARMONTH =
ZFIR057AT1-ZSFYEARMONTH .
ZMV_ZFIR057AT1-ZBLOCK_PUSH =
ZFIR057AT1-ZBLOCK_PUSH .
ZMV_ZFIR057AT1-TABNAME =
ZFIR057AT1-TABNAME .
ZMV_ZFIR057AT1-DBNAME =
ZFIR057AT1-DBNAME .
ZMV_ZFIR057AT1-ZSFSHOWFIELD =
ZFIR057AT1-ZSFSHOWFIELD .
<VIM_TOTAL_STRUC> = ZMV_ZFIR057AT1.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMV_ZFIR057AT1 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMV_ZFIR057AT1.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMV_ZFIR057AT1-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFIR057AT1 WHERE
  PROGNAME = ZMV_ZFIR057AT1-PROGNAME AND
  VARIANT = ZMV_ZFIR057AT1-VARIANT .
    IF SY-SUBRC = 0.
    DELETE ZFIR057AT1 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFIR057AT1 WHERE
  PROGNAME = ZMV_ZFIR057AT1-PROGNAME AND
  VARIANT = ZMV_ZFIR057AT1-VARIANT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFIR057AT1.
    ENDIF.
ZFIR057AT1-MANDT =
ZMV_ZFIR057AT1-MANDT .
ZFIR057AT1-PROGNAME =
ZMV_ZFIR057AT1-PROGNAME .
ZFIR057AT1-VARIANT =
ZMV_ZFIR057AT1-VARIANT .
ZFIR057AT1-ZSFYEARMONTH =
ZMV_ZFIR057AT1-ZSFYEARMONTH .
ZFIR057AT1-ZBLOCK_PUSH =
ZMV_ZFIR057AT1-ZBLOCK_PUSH .
ZFIR057AT1-TABNAME =
ZMV_ZFIR057AT1-TABNAME .
ZFIR057AT1-DBNAME =
ZMV_ZFIR057AT1-DBNAME .
ZFIR057AT1-ZSFSHOWFIELD =
ZMV_ZFIR057AT1-ZSFSHOWFIELD .
    IF SY-SUBRC = 0.
    UPDATE ZFIR057AT1 ##WARN_OK.
    ELSE.
    INSERT ZFIR057AT1 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMV_ZFIR057AT1-UPD_FLAG,
STATUS_ZMV_ZFIR057AT1-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMV_ZFIR057AT1.
  SELECT SINGLE * FROM ZFIR057AT1 WHERE
PROGNAME = ZMV_ZFIR057AT1-PROGNAME AND
VARIANT = ZMV_ZFIR057AT1-VARIANT .
ZMV_ZFIR057AT1-MANDT =
ZFIR057AT1-MANDT .
ZMV_ZFIR057AT1-PROGNAME =
ZFIR057AT1-PROGNAME .
ZMV_ZFIR057AT1-VARIANT =
ZFIR057AT1-VARIANT .
ZMV_ZFIR057AT1-ZSFYEARMONTH =
ZFIR057AT1-ZSFYEARMONTH .
ZMV_ZFIR057AT1-ZBLOCK_PUSH =
ZFIR057AT1-ZBLOCK_PUSH .
ZMV_ZFIR057AT1-TABNAME =
ZFIR057AT1-TABNAME .
ZMV_ZFIR057AT1-DBNAME =
ZFIR057AT1-DBNAME .
ZMV_ZFIR057AT1-ZSFSHOWFIELD =
ZFIR057AT1-ZSFSHOWFIELD .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMV_ZFIR057AT1 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMV_ZFIR057AT1-PROGNAME TO
ZFIR057AT1-PROGNAME .
MOVE ZMV_ZFIR057AT1-VARIANT TO
ZFIR057AT1-VARIANT .
MOVE ZMV_ZFIR057AT1-MANDT TO
ZFIR057AT1-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFIR057AT1'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFIR057AT1 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFIR057AT1'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
