*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMV_ZFIR057AT2..................................*
FORM GET_DATA_ZMV_ZFIR057AT2.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFIR057AT2 WHERE
(VIM_WHERETAB) .
    CLEAR ZMV_ZFIR057AT2 .
ZMV_ZFIR057AT2-MANDT =
ZFIR057AT2-MANDT .
ZMV_ZFIR057AT2-PROGNAME =
ZFIR057AT2-PROGNAME .
ZMV_ZFIR057AT2-VARIANT =
ZFIR057AT2-VARIANT .
ZMV_ZFIR057AT2-SAPFIELD =
ZFIR057AT2-SAPFIELD .
ZMV_ZFIR057AT2-NON_SAPFIELD =
ZFIR057AT2-NON_SAPFIELD .
<VIM_TOTAL_STRUC> = ZMV_ZFIR057AT2.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMV_ZFIR057AT2 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMV_ZFIR057AT2.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMV_ZFIR057AT2-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFIR057AT2 WHERE
  PROGNAME = ZMV_ZFIR057AT2-PROGNAME AND
  VARIANT = ZMV_ZFIR057AT2-VARIANT AND
  SAPFIELD = ZMV_ZFIR057AT2-SAPFIELD .
    IF SY-SUBRC = 0.
    DELETE ZFIR057AT2 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFIR057AT2 WHERE
  PROGNAME = ZMV_ZFIR057AT2-PROGNAME AND
  VARIANT = ZMV_ZFIR057AT2-VARIANT AND
  SAPFIELD = ZMV_ZFIR057AT2-SAPFIELD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFIR057AT2.
    ENDIF.
ZFIR057AT2-MANDT =
ZMV_ZFIR057AT2-MANDT .
ZFIR057AT2-PROGNAME =
ZMV_ZFIR057AT2-PROGNAME .
ZFIR057AT2-VARIANT =
ZMV_ZFIR057AT2-VARIANT .
ZFIR057AT2-SAPFIELD =
ZMV_ZFIR057AT2-SAPFIELD .
ZFIR057AT2-NON_SAPFIELD =
ZMV_ZFIR057AT2-NON_SAPFIELD .
    IF SY-SUBRC = 0.
    UPDATE ZFIR057AT2 ##WARN_OK.
    ELSE.
    INSERT ZFIR057AT2 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMV_ZFIR057AT2-UPD_FLAG,
STATUS_ZMV_ZFIR057AT2-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMV_ZFIR057AT2.
  SELECT SINGLE * FROM ZFIR057AT2 WHERE
PROGNAME = ZMV_ZFIR057AT2-PROGNAME AND
VARIANT = ZMV_ZFIR057AT2-VARIANT AND
SAPFIELD = ZMV_ZFIR057AT2-SAPFIELD .
ZMV_ZFIR057AT2-MANDT =
ZFIR057AT2-MANDT .
ZMV_ZFIR057AT2-PROGNAME =
ZFIR057AT2-PROGNAME .
ZMV_ZFIR057AT2-VARIANT =
ZFIR057AT2-VARIANT .
ZMV_ZFIR057AT2-SAPFIELD =
ZFIR057AT2-SAPFIELD .
ZMV_ZFIR057AT2-NON_SAPFIELD =
ZFIR057AT2-NON_SAPFIELD .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMV_ZFIR057AT2 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMV_ZFIR057AT2-PROGNAME TO
ZFIR057AT2-PROGNAME .
MOVE ZMV_ZFIR057AT2-VARIANT TO
ZFIR057AT2-VARIANT .
MOVE ZMV_ZFIR057AT2-SAPFIELD TO
ZFIR057AT2-SAPFIELD .
MOVE ZMV_ZFIR057AT2-MANDT TO
ZFIR057AT2-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFIR057AT2'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFIR057AT2 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFIR057AT2'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
